# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
   - -s -w -X "main.commit={{ .ShortCommit}} -X main.date={{ .Date}} -X main.version={{ .Version}}"  
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
    github:
      owner: csenol
      name: homebrew-plsd
    commit_author:
      name: csenol
      email: cagdassenol@gmail.com

    homepage: "https://github.com/csenol/plsd"

    # Your app's description.
    # Default is empty.
    description: "Develop Elasticsearch painless scripts painlessly"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    #skip_upload: true

